export interface GearItem{name:string;category:"Carry"|"Clothing"|"Food & water"|"Sleep"|"Safety"|"Technical";required:boolean;quantity:number;unitWeightG:number;consumable:boolean;worn:boolean;warning?:string;}
const core:GearItem[]=[{name:"Water containers",category:"Food & water",required:true,quantity:1,unitWeightG:180,consumable:false,worn:false},{name:"Food and snacks",category:"Food & water",required:true,quantity:1,unitWeightG:800,consumable:true,worn:false},{name:"Rain shell",category:"Clothing",required:true,quantity:1,unitWeightG:350,consumable:false,worn:false},{name:"First-aid kit",category:"Safety",required:true,quantity:1,unitWeightG:300,consumable:false,worn:false},{name:"Navigation backup",category:"Safety",required:true,quantity:1,unitWeightG:220,consumable:false,worn:false},{name:"Headlamp",category:"Safety",required:true,quantity:1,unitWeightG:100,consumable:false,worn:false}];
const sleep:GearItem[]=[{name:"Shelter",category:"Sleep",required:true,quantity:1,unitWeightG:1500,consumable:false,worn:false},{name:"Sleeping bag",category:"Sleep",required:true,quantity:1,unitWeightG:1000,consumable:false,worn:false},{name:"Sleeping mat",category:"Sleep",required:true,quantity:1,unitWeightG:500,consumable:false,worn:false},{name:"Stove and fuel",category:"Food & water",required:true,quantity:1,unitWeightG:650,consumable:false,worn:false}];
const technical:GearItem[]=[{name:"Helmet",category:"Technical",required:true,quantity:1,unitWeightG:350,consumable:false,worn:true,warning:"Use only with appropriate training and qualified route guidance."},{name:"Harness",category:"Technical",required:true,quantity:1,unitWeightG:400,consumable:false,worn:true,warning:"Technical equipment selection and use require qualified instruction."},{name:"Crampons",category:"Technical",required:true,quantity:1,unitWeightG:900,consumable:false,worn:false,warning:"Compatibility and conditions must be checked by a qualified guide."}];
const add=(...groups:GearItem[][])=>groups.flat().map(v=>({...v}));
export const STRUCTURED_GEAR_TEMPLATES={"Short day hike":add(core.slice(0,5)),"Full-day mountain hike":add(core),"Overnight trek":add(core,sleep),"Multi-day supported trek":add(core,sleep.slice(1,3)),"Multi-day self-supported trek":add(core,sleep),"High-altitude trek":add(core,sleep.slice(1,3),[{name:"Insulated layer",category:"Clothing",required:true,quantity:1,unitWeightG:500,consumable:false,worn:false}]),"Cold-weather trek":add(core,sleep,[{name:"Cold-weather gloves",category:"Clothing",required:true,quantity:1,unitWeightG:180,consumable:false,worn:true}]),"Hot and exposed route":add(core,[{name:"Sun hat",category:"Clothing",required:true,quantity:1,unitWeightG:90,consumable:false,worn:true},{name:"Extra water capacity",category:"Food & water",required:true,quantity:1,unitWeightG:100,consumable:false,worn:false}]),"Wet or tropical route":add(core,[{name:"Dry bags",category:"Carry",required:true,quantity:3,unitWeightG:70,consumable:false,worn:false}]),"Technical equipment review":add(core,technical)} as const;
export type StructuredGearTemplateName=keyof typeof STRUCTURED_GEAR_TEMPLATES;
export const GEAR_TEMPLATES={"Day Hike":STRUCTURED_GEAR_TEMPLATES["Full-day mountain hike"].map(v=>v.name),Overnight:STRUCTURED_GEAR_TEMPLATES["Overnight trek"].map(v=>v.name),"Multi-day":STRUCTURED_GEAR_TEMPLATES["Multi-day self-supported trek"].map(v=>v.name),"Alpine / Technical":STRUCTURED_GEAR_TEMPLATES["Technical equipment review"].map(v=>v.name)} as const;
export type GearTemplateName=keyof typeof GEAR_TEMPLATES;
export function gearTotals(items:GearItem[],packed:string[]){const selected=items.filter(i=>packed.includes(i.name));const sum=(list:GearItem[])=>list.reduce((total,i)=>total+i.unitWeightG*i.quantity,0);const required=items.filter(i=>i.required);return{baseWeightG:sum(selected.filter(i=>!i.consumable&&!i.worn)),consumableWeightG:sum(selected.filter(i=>i.consumable)),wornWeightG:sum(selected.filter(i=>i.worn)),totalWeightG:sum(selected),completion:items.length?Math.round(selected.length/items.length*100):0,missingCritical:required.filter(i=>!packed.includes(i.name)).map(i=>i.name)}}
