export type TripStatus="draft"|"planned"|"active"|"completed"|"cancelled";
export interface SavedTrip{schemaVersion:2;id:string;destinationId?:string;name:string;region:string;date:string;expectedReturn?:string;duration:string;distance:string;type:string;routeVariant?:string;accessLocation?:string;transportNotes?:string;accommodationStyle?:string;guideDetails?:string;permitStatus?:string;groupSize?:string;medicalNotes?:string;notes:string;contactName:string;contactPhone:string;checkInPlan:string;gear:string[];coordinates:{lat:number;lng:number}|null;officialSources?:{label:string;url:string}[];status:TripStatus;createdAt:string;updatedAt:string;}
export interface DeletedTrip{trip:SavedTrip;deletedAt:string}
export const TRIPS_STORAGE_KEY="traildesk_trips",TRIPS_TRASH_KEY="traildesk_trips_trash_v1",STORAGE_VERSION=2,TRASH_RETENTION_DAYS=30;
export interface TripsReadResult{trips:SavedTrip[];recovered:number;error:string|null}
const statuses:TripStatus[]=["draft","planned","active","completed","cancelled"];
function migrate(value:unknown):SavedTrip|null{if(!value||typeof value!=="object")return null;const v=value as Record<string,unknown>;if(typeof v.id!=="string"||typeof v.name!=="string")return null;const now=new Date().toISOString();return{schemaVersion:2,id:v.id,destinationId:typeof v.destinationId==="string"?v.destinationId:undefined,name:v.name,region:typeof v.region==="string"?v.region:"",date:typeof v.date==="string"?v.date:"",expectedReturn:typeof v.expectedReturn==="string"?v.expectedReturn:undefined,duration:typeof v.duration==="string"?v.duration:"",distance:typeof v.distance==="string"?v.distance:"",type:typeof v.type==="string"?v.type:"Day Hike",routeVariant:typeof v.routeVariant==="string"?v.routeVariant:undefined,accessLocation:typeof v.accessLocation==="string"?v.accessLocation:undefined,transportNotes:typeof v.transportNotes==="string"?v.transportNotes:undefined,accommodationStyle:typeof v.accommodationStyle==="string"?v.accommodationStyle:undefined,guideDetails:typeof v.guideDetails==="string"?v.guideDetails:undefined,permitStatus:typeof v.permitStatus==="string"?v.permitStatus:undefined,groupSize:typeof v.groupSize==="string"?v.groupSize:undefined,medicalNotes:typeof v.medicalNotes==="string"?v.medicalNotes:undefined,notes:typeof v.notes==="string"?v.notes:"",contactName:typeof v.contactName==="string"?v.contactName:"",contactPhone:typeof v.contactPhone==="string"?v.contactPhone:"",checkInPlan:typeof v.checkInPlan==="string"?v.checkInPlan:"",gear:Array.isArray(v.gear)?v.gear.filter((i):i is string=>typeof i==="string"):[],coordinates:v.coordinates&&typeof v.coordinates==="object"&&typeof (v.coordinates as Record<string,unknown>).lat==="number"&&typeof (v.coordinates as Record<string,unknown>).lng==="number"?{lat:(v.coordinates as {lat:number}).lat,lng:(v.coordinates as {lng:number}).lng}:null,officialSources:Array.isArray(v.officialSources)?v.officialSources.filter((i):i is {label:string;url:string}=>Boolean(i&&typeof i==="object"&&typeof (i as Record<string,unknown>).label==="string"&&typeof (i as Record<string,unknown>).url==="string")):undefined,status:typeof v.status==="string"&&statuses.includes(v.status as TripStatus)?v.status as TripStatus:"draft",createdAt:typeof v.createdAt==="string"?v.createdAt:now,updatedAt:typeof v.updatedAt==="string"?v.updatedAt:now};}
export function parseTrips(raw:string|null):TripsReadResult{if(!raw)return{trips:[],recovered:0,error:null};try{const parsed:unknown=JSON.parse(raw);if(!Array.isArray(parsed))return{trips:[],recovered:0,error:"Stored trip data was not a valid list."};const trips=parsed.map(migrate).filter((v):v is SavedTrip=>Boolean(v));return{trips,recovered:parsed.length-trips.length,error:parsed.length&&!trips.length?"No valid trip records could be recovered.":null}}catch{return{trips:[],recovered:0,error:"Stored trip data could not be parsed."}}}
export function readTripsResult():TripsReadResult{try{return parseTrips(window.localStorage.getItem(TRIPS_STORAGE_KEY))}catch{return{trips:[],recovered:0,error:"Browser storage is unavailable."}}}
export function readTrips(){return readTripsResult().trips}
export function writeTrips(trips:SavedTrip[]){window.localStorage.setItem(TRIPS_STORAGE_KEY,JSON.stringify(trips.map(t=>({...t,schemaVersion:2 as const}))));window.localStorage.setItem(`${TRIPS_STORAGE_KEY}_version`,String(STORAGE_VERSION));}
export function parseTrash(raw:string|null,now=Date.now()):DeletedTrip[]{if(!raw)return[];try{const parsed:unknown=JSON.parse(raw);if(!Array.isArray(parsed))return[];const cutoff=now-TRASH_RETENTION_DAYS*86400000;return parsed.flatMap(value=>{if(!value||typeof value!=="object")return[];const row=value as Record<string,unknown>,trip=migrate(row.trip);return trip&&typeof row.deletedAt==="string"&&Date.parse(row.deletedAt)>=cutoff?[{trip,deletedAt:row.deletedAt}]:[]})}catch{return[]}}
export function readTrash(){try{return parseTrash(window.localStorage.getItem(TRIPS_TRASH_KEY))}catch{return[]}}
export function writeTrash(items:DeletedTrip[]){window.localStorage.setItem(TRIPS_TRASH_KEY,JSON.stringify(items))}
export function duplicateTrip(trip:SavedTrip,now=new Date().toISOString()):SavedTrip{return{...trip,id:crypto.randomUUID(),name:`${trip.name} (copy)`,status:"draft",createdAt:now,updatedAt:now}}
export function validateTripImport(value:unknown,existing:SavedTrip[]=[]){const list=Array.isArray(value)?value:[value],trips=list.map(migrate).filter((v):v is SavedTrip=>Boolean(v)),ids=new Set(existing.map(t=>t.id));return{trips,conflicts:trips.filter(t=>ids.has(t.id)).map(t=>t.id),errors:list.length===trips.length?[]:[`${list.length-trips.length} invalid record(s) were rejected.`]}}
export function isValidIsoDate(value:string){return /^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(`${value}T00:00:00Z`))}
export function validateTripDates(departure:string,expectedReturn?:string){if(!isValidIsoDate(departure))return"Enter a valid departure date.";if(expectedReturn&&Date.parse(expectedReturn)<Date.parse(`${departure}T00:00`))return"Expected return must be after departure.";return null}
export function tripBrief(t:SavedTrip){return["TRAILDESK TRIP BRIEF",t.name,`${t.region}${t.date?` · ${t.date}`:""}`,`Status: ${t.status}`,t.expectedReturn?`Expected return: ${t.expectedReturn}`:"",t.routeVariant?`Route: ${t.routeVariant}`:"",t.groupSize?`Group size: ${t.groupSize}`:"",t.accessLocation?`Access: ${t.accessLocation}`:"",t.coordinates?`Destination reference: ${t.coordinates.lat}, ${t.coordinates.lng}`:"",t.transportNotes?`Transport: ${t.transportNotes}`:"",t.accommodationStyle?`Accommodation: ${t.accommodationStyle}`:"",t.guideDetails?`Guide: ${t.guideDetails}`:"",t.permitStatus?`Permit: ${t.permitStatus}`:"",t.duration?`Expected duration: ${t.duration}`:"",t.notes?`Route notes: ${t.notes}`:"",t.contactName?`Emergency contact: ${t.contactName} ${t.contactPhone}`:"",t.checkInPlan?`Manual check-in plan: ${t.checkInPlan}`:"",t.medicalNotes?`Medical note: ${t.medicalNotes}`:"",...(t.officialSources??[]).map(s=>`${s.label}: ${s.url}`),"TrailDesk does not monitor this trip, notify contacts, provide navigation, or contact emergency services."].filter(Boolean).join("\n")}
