import type {Metadata} from "next";
import Image from "next/image";
import Link from "next/link";
import {ArrowRight,ExternalLink,ShieldAlert} from "lucide-react";
import {notFound} from "next/navigation";
import {AppShell} from "@/components/app-shell";
import {MapActions} from "@/components/map-actions";
import {ReviewPanel} from "@/components/review-panel";
import {StatusBadge} from "@/components/status-badge";
import {DESTINATIONS,findDestination} from "@/app/lib/destinations";
import {DESTINATION_GALLERY,PHOTO_CREDITS} from "@/app/lib/photo-credits";
import "./guide.css";
import "./gallery.css";
import "./gallery-polish.css";

export function generateStaticParams(){return DESTINATIONS.map(({slug})=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const d=findDestination(slug);if(!d)return{};return{title:`${d.name}, ${d.country} trail guide`,description:d.overview,alternates:{canonical:`/explore/${d.slug}`},openGraph:{title:`${d.name} trail guide · TrailDesk`,description:d.overview,images:d.image?[{url:d.image,alt:d.imageAlt}]:undefined}};}

export default async function DestinationGuide({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const d=findDestination(slug);if(!d)notFound();const credit=PHOTO_CREDITS[d.id],gallery=DESTINATION_GALLERY[d.id]??[],related=d.relatedDestinationIds.map(findDestination).filter(Boolean);return <AppShell><main id="main-content" className="guide-page">
<nav className="container breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/explore">Explore</Link><span>/</span><span aria-current="page">{d.name}</span></nav>
<header className={`guide-hero${d.image?" has-image":""}`}>{d.image?<Image src={d.image} alt={d.imageAlt} fill priority sizes="100vw"/>:null}<div className="guide-hero-shade"/><div className="container guide-hero-inner"><p className="eyebrow">{d.continent} · {d.country}</p><h1>{d.name}</h1><p>{d.overview}</p><div className="cluster"><StatusBadge>{d.difficulty}</StatusBadge><span>{d.routeType}</span><span>{d.typicalDuration}</span></div>{credit?<p className="guide-credit">Photograph by <a href={credit.source} target="_blank" rel="noopener noreferrer">{credit.author}</a> · <a href={credit.licenseUrl||credit.source} target="_blank" rel="noopener noreferrer">{credit.license}</a></p>:null}</div></header>
<nav className="guide-index" aria-label="On this page"><div className="container"><span>On this page</span><a href="#essential-facts">Facts</a><a href="#route-character">Route</a>{gallery.length?<a href="#field-view">Field view</a>:null}<a href="#preparation">Preparation</a><a href="#sources">Sources</a></div></nav>
<div className="container guide-layout"><article className="guide-content">
<section id="essential-facts" className="guide-facts" aria-label="Essential facts"><dl><div><dt>Country / region</dt><dd>{d.country}<small>{d.region}</small></dd></div><div><dt>Route type</dt><dd>{d.routeType}<small>{d.category}</small></dd></div><div><dt>Highest point</dt><dd>{d.highestPoint}</dd></div><div><dt>Distance</dt><dd>{d.distance}</dd></div><div><dt>Typical duration</dt><dd>{d.typicalDuration}</dd></div><div><dt>Common season</dt><dd>{d.seasonSummary}</dd></div></dl></section>
<section id="route-character" className="guide-editorial"><p className="eyebrow">Trail brief</p><h2>What the route demands</h2><p>{d.routeCharacter}</p><div className="guide-two-column"><div><h3>Terrain</h3><ul>{d.terrain.map(v=><li key={v}>{v}</li>)}</ul></div><div><h3>Fitness and technical level</h3><p>{d.fitnessLevel}</p><p>{d.technicalLevel}</p></div></div></section>
{gallery.length?<section id="field-view" className="guide-gallery"><div className="guide-section-heading"><div><p className="eyebrow">Field view</p><h2>See the ground, not just the summit.</h2></div><p>Documentary photographs from the route environment. No generated scenery or visual simulation.</p></div>{gallery.map(photo=><figure key={photo.src}><div className="guide-gallery-image"><Image src={photo.src} alt={photo.alt} fill sizes="(max-width: 900px) 100vw, 70vw"/></div><figcaption><span>{photo.caption}</span><small>Photo: <a href={photo.source} target="_blank" rel="noopener noreferrer">{photo.author}</a> · <a href={photo.licenseUrl} target="_blank" rel="noopener noreferrer">{photo.license}</a></small></figcaption></figure>)}</section>:null}
<section className="guide-details"><div><p className="eyebrow">Altitude</p><h2>Height and acclimatisation</h2><p>{d.altitudeNote}</p></div><div><p className="eyebrow">Conditions</p><h2>Weather and seasonality</h2><p>{d.weatherNote}</p></div><div><p className="eyebrow">Water</p><h2>Resupply planning</h2><p>{d.waterNote}</p></div><div><p className="eyebrow">Access</p><h2>Transport and start area</h2><p>{d.accessNote}</p></div><div><p className="eyebrow">Requirements</p><h2>Permits and guides</h2><p>{d.permitNote}</p><p>{d.guideNote}</p></div><div><p className="eyebrow">Overnight pattern</p><h2>Accommodation</h2><p>{d.accommodationStyle}</p></div></section>
<section id="preparation" className="guide-planning"><div><p className="eyebrow">Preparation checklist</p><h2>Verify before departure</h2><ul>{d.preparationChecklist.map(v=><li key={v}>{v}</li>)}</ul></div><div className="guide-risk"><ShieldAlert size={28}/><h3>Main planning risks</h3><ul>{d.mainRisks.map(v=><li key={v}>{v}</li>)}</ul><p>{d.emergencyPlanningNote}</p></div></section>
<section className="guide-map"><p className="eyebrow">Map and directions</p><h2>A real reference point, not a route line.</h2><MapActions destination={d}/></section><ReviewPanel destinationId={d.id} destinationName={d.name}/>
<section id="sources" className="guide-sources"><p className="eyebrow">Official references</p><h2>Check the responsible source.</h2><p>TrailDesk reviewed this record on <time dateTime={d.lastReviewedAt}>{d.lastReviewedAt}</time>. Rules and conditions can change after that date.</p><ul>{d.officialSources.map(source=><li key={source.url}><a href={source.url} target="_blank" rel="noopener noreferrer">{source.label} <ExternalLink size={14}/></a></li>)}</ul></section>
{related.length?<section className="guide-related"><p className="eyebrow">Related research</p><h2>Compare before choosing.</h2><div>{related.map(item=>item?<Link href={`/explore/${item.slug}`} key={item.id}>{item.image?<span className="guide-related-image"><Image src={item.image} alt="" fill sizes="(max-width: 620px) 100vw, 35vw"/></span>:null}<span>{item.country}</span><strong>{item.name}</strong><small>{item.routeType} · {item.difficulty} · {item.typicalDuration}</small><ArrowRight size={16}/></Link>:null)}</div></section>:null}
</article><aside className="guide-aside"><div><p className="eyebrow">Build a practical brief</p><h2>Plan this trek</h2><p>Start with catalogue context, then add your own dates, route variant, contacts, and decisions.</p><Link className="button button-primary" href={`/plan?from=${d.id}`}>Plan this trek <ArrowRight size={16}/></Link><small>Saved in this browser only.</small></div><div className="notice"><strong>Planning aid only.</strong> TrailDesk is not navigation, live tracking, weather, or emergency response.</div></aside></div>
</main></AppShell>}
