"use client";
import {RotateCcw,Scale} from "lucide-react";
import {useEffect,useMemo,useState} from "react";
import {AppShell} from "@/components/app-shell";
import {STRUCTURED_GEAR_TEMPLATES,gearTotals,type StructuredGearTemplateName} from "@/app/lib/gear";
const STORAGE_KEY="traildesk_gear_v1";type PackedState=Record<string,string[]>;const kg=(g:number)=>`${(g/1000).toFixed(2)} kg`;
export default function GearPage(){const templates=Object.keys(STRUCTURED_GEAR_TEMPLATES) as StructuredGearTemplateName[];const[active,setActive]=useState<StructuredGearTemplateName>("Short day hike");const[packed,setPacked]=useState<PackedState>({});const[ready,setReady]=useState(false);const[error,setError]=useState("");
 useEffect(()=>{const timer=setTimeout(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const value=JSON.parse(raw);setPacked(value.packed??{})}}catch{setError("The saved checklist could not be read.")}setReady(true)},0);return()=>clearTimeout(timer)},[]);const items=useMemo(()=>STRUCTURED_GEAR_TEMPLATES[active].map(v=>({...v})),[active]);const done=useMemo(()=>packed[active]??[],[active,packed]);const totals=useMemo(()=>gearTotals(items,done),[items,done]);const save=(next:PackedState)=>{setPacked(next);try{localStorage.setItem(STORAGE_KEY,JSON.stringify({schemaVersion:2,packed:next}))}catch{setError("The browser refused the checklist update.")}};const toggle=(name:string)=>save({...packed,[active]:done.includes(name)?done.filter(v=>v!==name):[...done,name]});
 return <AppShell><main id="main-content"><header className="page-header"><div className="container"><p className="eyebrow">Reusable preparation lists</p><h1>Review weight, not just item count.</h1><p className="lede">Ten route-pattern templates separate carried, worn, and consumable weight. They are planning prompts, not a guarantee of completeness or safe equipment use.</p></div></header><div className="container"><div className="notice"><strong>General guidance only.</strong> Technical equipment and use must be reviewed with a qualified guide. A checklist is not training.</div>{error&&<p role="alert">{error}</p>}<section className="gear-layout"><nav className="gear-tabs" aria-label="Gear templates">{templates.map(v=><button key={v} aria-pressed={active===v} onClick={()=>setActive(v)}>{v}<span>{STRUCTURED_GEAR_TEMPLATES[v].length} starting items</span></button>)}</nav><div className="card form-card"><div className="split"><div><p className="eyebrow">{totals.completion}% reviewed</p><h2>{active}</h2></div><button className="button button-small" onClick={()=>save({...packed,[active]:[]})}><RotateCcw size={14}/> Reset</button></div><div className="gear-metrics"><div><Scale size={18}/><span>Base weight</span><strong>{kg(totals.baseWeightG)}</strong></div><div><span>Consumables</span><strong>{kg(totals.consumableWeightG)}</strong></div><div><span>Worn</span><strong>{kg(totals.wornWeightG)}</strong></div><div><span>Total selected</span><strong>{kg(totals.totalWeightG)}</strong></div></div>{totals.missingCritical.length>0&&<div className="notice"><strong>{totals.missingCritical.length} required prompts not marked</strong><p>{totals.missingCritical.join(" · ")}</p></div>}{!ready?<p>Loading this browser’s checklist…</p>:<div className="structured-gear-list">{Array.from(new Set(items.map(i=>i.category))).map(category=><section key={category}><h3>{category}</h3>{items.filter(i=>i.category===category).map(item=><label className={`gear-row${done.includes(item.name)?" is-packed":""}`} key={item.name}><input type="checkbox" checked={done.includes(item.name)} onChange={()=>toggle(item.name)}/><span><strong>{item.name}</strong><small>{item.required?"Required prompt":"Optional"} · {item.quantity} × {item.unitWeightG} g{item.consumable?" · consumable":""}{item.worn?" · worn":""}</small>{item.warning&&<small className="gear-warning">{item.warning}</small>}</span></label>)}</section>)}</div>}</div></section></div></main></AppShell>}
