"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Menu, Plus, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { BrandLogo } from "./brand-logo";

const links=[{href:"/explore",label:"Explore"},{href:"/regions",label:"Regions"},{href:"/trips",label:"My trips"},{href:"/gear",label:"Gear"},{href:"/about",label:"About"}];
export function SiteHeader(){const pathname=usePathname();const [open,setOpen]=useState(false);const menuButton=useRef<HTMLButtonElement>(null);const nav=useRef<HTMLElement>(null);
 useEffect(()=>{if(!open)return;document.body.classList.add("nav-open");const focusable=nav.current?.querySelectorAll<HTMLElement>("a,button")??[];focusable[0]?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape"){setOpen(false);menuButton.current?.focus()}if(event.key==="Tab"&&focusable.length){const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}};addEventListener("keydown",key);return()=>{document.body.classList.remove("nav-open");removeEventListener("keydown",key)}},[open]);
 return <header className="site-header"><div className="header-inner"><Link href="/" className="brand-link" onClick={()=>setOpen(false)}><BrandLogo/></Link><button ref={menuButton} className="menu-button" type="button" aria-expanded={open} aria-controls="primary-nav" onClick={()=>setOpen(v=>!v)}><span className="sr-only">{open?"Close navigation":"Open navigation"}</span>{open?<X aria-hidden="true"/>:<Menu aria-hidden="true"/>}</button><nav ref={nav} id="primary-nav" className={`primary-nav${open?" is-open":""}`} aria-label="Primary navigation">{links.map(link=><Link key={link.href} href={link.href} aria-current={pathname===link.href||pathname.startsWith(`${link.href}/`)?"page":undefined} onClick={()=>setOpen(false)}>{link.label}</Link>)}<Link href="/plan" className="button button-primary button-small" aria-current={pathname==="/plan"?"page":undefined} onClick={()=>setOpen(false)}><Plus size={16} aria-hidden="true"/> Plan a trip</Link></nav></div></header>}
