"use client";
import Link from "next/link";
import {CheckCircle2,ClipboardCheck,Copy} from "lucide-react";
import {useEffect,useMemo,useState} from "react";
import {AppShell} from "@/components/app-shell";
import {briefGaps,departureChecks,parseReadiness,READINESS_STORAGE_KEY,readinessLabel,type DepartureCheckId,type ReadinessRecord} from "@/app/lib/readiness";
import {readTrips,type SavedTrip} from "@/app/lib/trips";
import "./readiness.css";

export default function ReadinessPage(){const[trips,setTrips]=useState<SavedTrip[]>([]);const[records,setRecords]=useState<Record<string,ReadinessRecord>>({});const[selected,setSelected]=useState("");const[message,setMessage]=useState("");const[ready,setReady]=useState(false);
 useEffect(()=>{const timer=setTimeout(()=>{const saved=readTrips();setTrips(saved);try{setRecords(parseReadiness(localStorage.getItem(READINESS_STORAGE_KEY)))}catch{}const requested=new URLSearchParams(location.search).get("trip");setSelected(saved.some(t=>t.id===requested)?requested??"":saved[0]?.id??"");setReady(true)},0);return()=>clearTimeout(timer)},[]);
 const trip=useMemo(()=>trips.find(item=>item.id===selected),[trips,selected]);const record=trip?records[trip.id]:undefined;const gaps=trip?briefGaps(trip):[];const state=trip?readinessLabel(trip,record):null;
 const persist=(tripId:string,next:ReadinessRecord)=>{const all={...records,[tripId]:next};try{localStorage.setItem(READINESS_STORAGE_KEY,JSON.stringify(all));setRecords(all);setMessage("Departure review saved in this browser.")}catch{setMessage("This browser could not save the departure review. Export the trip brief before leaving this page.")}};
 const toggle=(id:DepartureCheckId)=>{if(!trip)return;const checks=record?.checks??[];persist(trip.id,{schemaVersion:1,tripId:trip.id,checks:checks.includes(id)?checks.filter(value=>value!==id):[...checks,id],note:record?.note??"",updatedAt:new Date().toISOString()})};
 const note=(value:string)=>{if(!trip)return;persist(trip.id,{schemaVersion:1,tripId:trip.id,checks:record?.checks??[],note:value.slice(0,600),updatedAt:new Date().toISOString()})};
 const copy=async()=>{if(!trip||!state)return;const checked=new Set(record?.checks??[]);const text=[`TRAILDESK DEPARTURE CHECK — ${trip.name}`,`${state.label}: ${state.detail}`,"",...departureChecks.map(item=>`${checked.has(item.id)?"[x]":"[ ]"} ${item.label}`),record?.note?`\nPlan B / final note: ${record.note}`:"","","TrailDesk does not monitor this trip or certify readiness. Confirm current information and carry independent navigation, communication, and emergency systems."].filter(Boolean).join("\n");try{await navigator.clipboard.writeText(text);setMessage("Departure check copied.")}catch{setMessage("Clipboard access was unavailable.")}};
 return <AppShell><main id="main-content"><header className="page-header"><div className="container"><p className="eyebrow">Before leaving signal</p><h1>Run a departure check.</h1><p className="lede">Turn a saved plan into a brief someone else can understand, then record the final checks that must happen close to departure.</p></div></header><div className="container">{!ready?<div className="empty-state">Opening saved plans…</div>:!trips.length?<div className="empty-state"><ClipboardCheck size={30}/><h2>No trip is ready to review yet</h2><p>Create a trip brief first. The departure check uses its dates, route, access point, contact agreement, sources, and gear notes.</p><Link className="button button-primary" href="/plan">Build a trip plan</Link></div>:<><label className="field narrow">Trip to review<select value={selected} onChange={event=>setSelected(event.target.value)}>{trips.map(item=><option value={item.id} key={item.id}>{item.name} — {item.date||"date not set"}</option>)}</select></label>{trip&&state&&<div className="readiness-layout section"><section className="card form-card" aria-labelledby="departure-checks"><p className="eyebrow">Final review · {record?.checks.length??0} of {departureChecks.length}</p><h2 id="departure-checks">Checks that expire with changing conditions</h2><p>Complete these near departure. A checked box records your review; it does not prove the route is safe.</p><div className="readiness-checks">{departureChecks.map(item=><label className="readiness-check" key={item.id}><input type="checkbox" checked={record?.checks.includes(item.id)??false} onChange={()=>toggle(item.id)}/><span>{item.label}</span></label>)}</div><div className="field"><label htmlFor="plan-b">Plan B, turnaround point, or final change</label><textarea id="plan-b" maxLength={600} value={record?.note??""} onChange={event=>note(event.target.value)}/><small>{record?.note.length??0}/600 characters · saved locally</small></div></section><aside className="card form-card readiness-side" aria-live="polite"><CheckCircle2 size={26}/><p className="eyebrow">Current state</p><h2>{state.label}</h2><p>{state.detail}</p>{gaps.length>0&&<><h3>Fix in the trip brief</h3><ul className="gap-list">{gaps.map(gap=><li key={gap}>{gap}</li>)}</ul><Link className="button" href={`/plan?edit=${trip.id}`}>Edit trip brief</Link></>}<button className="button button-primary" onClick={copy}><Copy size={15}/> Copy departure check</button><p className="readiness-meta">{record?.updatedAt?`Last reviewed ${new Date(record.updatedAt).toLocaleString()}.`:"No departure checks recorded yet."}</p></aside></div>}</>}{message&&<p role="status">{message}</p>}</div></main></AppShell>}
